---
title: "Untitled"
output: html_document
---

```{r, message=FALSE, warning=FALSE, fig.height = 9, fig.width = 9}
rm(list=ls())
library(vegan)
library(SpiecEasi)
library(psych)##
library(igraph)
#setwd("~/GaoC/R")
library(beepr)
setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")

load("Bac.Fung.data.prep.stopby8datasets.RSLZxBF.Rarefaction.2021.08.10.rdata")

BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]

#habitat <- "Root"; treatment <- "Control"; tpA <- 2; tpB <- 9

fq <- 7; abu <- 19; 

SpMan<-function(fq, abu, treatment, tpA, tpB){
  
  d1 <- d1.raw [env.R$Treatment1==treatment & env.R$TP > tpA & env.R$TP < tpB , ]
  d1 <- d1 [,specnumber(t(d1)) > fq & colSums(d1)> abu]
  d2 <- d2.raw [env.R$Treatment1==treatment & env.R$TP > tpA & env.R$TP < tpB, ]
  d2 <- d2[, specnumber(t(d2)) > fq & colSums(d2)> abu]
  env.R.tmp0 <- env.R [env.R$Treatment1==treatment & env.R$TP > tpA & env.R$TP < tpB , ]
  
  d3 <- d3.raw [env.Z$Treatment1==treatment & env.Z$TP > tpA & env.Z$TP < tpB , ]
  d3 <- d3 [,specnumber(t(d3)) > fq & colSums(d3)> abu]
  d4 <- d4.raw [env.Z$Treatment1==treatment & env.Z$TP > tpA & env.Z$TP < tpB , ]
  d4 <- d4 [,specnumber(t(d4)) > fq & colSums(d4)> abu]
  env.Z.tmp0 <- env.Z [env.Z$Treatment1==treatment & env.Z$TP > tpA & env.Z$TP < tpB , ]
  
  d5 <- d5.raw [env.S$Treatment1==treatment & env.S$TP > tpA & env.S$TP < tpB, ]
  d5 <- d5[, specnumber(t(d5)) > fq & colSums(d5)> abu]
  d6 <- d6.raw [env.S$Treatment1==treatment & env.S$TP > tpA & env.S$TP < tpB , ]
  d6 <- d6 [,specnumber(t(d6)) > fq & colSums(d6)> abu]
  env.S.tmp0 <- env.S [env.S$Treatment1==treatment & env.S$TP > tpA & env.S$TP < tpB , ]
  
  d7 <- d7.raw [env.L$Treatment1==treatment & env.L$TP > tpA & env.L$TP < tpB , ]
  d7 <- d7[,specnumber(t(d7)) > fq & colSums(d7)> abu]
  d8 <- d8.raw [env.L$Treatment1==treatment & env.L$TP > tpA & env.L$TP < tpB, ]
  d8 <- d8[, specnumber(t(d8)) > fq & colSums(d8)> abu]
  env.L.tmp0 <- env.L [env.L$Treatment1==treatment & env.L$TP > tpA & env.L$TP < tpB , ]
  
  saveRDS(env.L.tmp0, paste0("BFT.SpMan.df.2021.08.16/data.env.Leaf.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(env.S.tmp0, paste0("BFT.SpMan.df.2021.08.16/data.env.Soil.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(env.Z.tmp0, paste0("BFT.SpMan.df.2021.08.16/data.env.Rhizosphere.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(env.R.tmp0, paste0("BFT.SpMan.df.2021.08.16/data.env.Root.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  saveRDS(d1, paste0("BFT.SpMan.df.2021.08.16/data.bac.Root.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(d2, paste0("BFT.SpMan.df.2021.08.16/data.fung.Root.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  saveRDS(d3, paste0("BFT.SpMan.df.2021.08.16/data.bac.Rhizosphere.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(d4, paste0("BFT.SpMan.df.2021.08.16/data.fung.Rhizosphere.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  saveRDS(d5, paste0("BFT.SpMan.df.2021.08.16/data.bac.Soil.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(d6, paste0("BFT.SpMan.df.2021.08.16/data.fung.Soil.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  saveRDS(d7, paste0("BFT.SpMan.df.2021.08.16/data.bac.Leaf.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  saveRDS(d8, paste0("BFT.SpMan.df.2021.08.16/data.fung.Leaf.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  d12<-cbind(d1,d2)
  spman.d12 = corr.test(d12, use="pairwise",method="spearman",adjust="fdr", alpha=.05, ci=FALSE)
  saveRDS(spman.d12, paste0("BFT.SpMan.df.2021.08.16/SpMan.crossBF.Root.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))

  d34<-cbind(d3,d4)
  spman.d34 = corr.test(d34, use="pairwise",method="spearman",adjust="fdr", alpha=.05, ci=FALSE)
  saveRDS(spman.d34, paste0("BFT.SpMan.df.2021.08.16/SpMan.crossBF.Rhizosphere.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  d56<-cbind(d5,d6)
  spman.d56 = corr.test(d56, use="pairwise",method="spearman",adjust="fdr", alpha=.05, ci=FALSE)
  saveRDS(spman.d56, paste0("BFT.SpMan.df.2021.08.16/SpMan.crossBF.Soil.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  d78<-cbind(d7,d8)
  spman.d78 = corr.test(d78, use="pairwise",method="spearman",adjust="fdr", alpha=.05, ci=FALSE)
  saveRDS(spman.d78, paste0("BFT.SpMan.df.2021.08.16/SpMan.crossBF.Leaf.", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
beep()
}

#SpMan(fq, abu, "Control", 2, 9)
#SpMan(fq, abu, "Pre_flowering_drought", 2, 9)
#SpMan(fq, abu, "Control", 8, 18)
#SpMan(fq, abu, "Pre_flowering_drought", 8, 18)
#SpMan(fq, abu, "Control", 9, 18)
#SpMan(fq, abu, "Post_flowering_drought", 9, 18)

######################################
# significant positive correlations #
#####################################

#setwd("~/GaoC/R")
setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")
BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]


habitat <- "Root"; treatment <- "Control"; tpA <- 2; tpB <- 9

r.cutoff = 0.6
p.cutoff = 0.05

SpMan.Rsig<-function(fq, abu, habitat, treatment, tpA, tpB){
  d1 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/data.bac.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  d2 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/data.fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  d12 <- data.frame(d1, d2)
  
  
  spman.r0 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/SpMan.crossBF.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))

  Cor<-as.matrix(spman.r0$r)
  Cor.df<-data.frame(row=rownames(Cor)[row(Cor)[upper.tri(Cor)]], 
                     col=colnames(Cor)[col(Cor)[upper.tri(Cor)]], Cor=Cor[upper.tri(Cor)])
  
  P0<-as.matrix(spman.r0$p)
  P.df<-data.frame(row=rownames(P0)[row(P0)[upper.tri(P0)]], 
                     col=colnames(P0)[col(P0)[upper.tri(P0)]], p=P0[upper.tri(P0)])
  
  df <- data.frame(Cor.df,  P.df, Habitat = habitat, Treatment = treatment, TPA = tpA)
  da.tmp<-df.sig<- df[ df$Cor > r.cutoff & df$p < p.cutoff,] 
  V1<-data.frame("v1"=da.tmp$row); V2<-data.frame("v2"=da.tmp$col)
  IDsub1<-ID.tmp[ID.tmp$OTU.ID %in% V1$v1, ]; IDsub2<-ID.tmp[ID.tmp$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  df.tmp<-data.frame(da.tmp, M1, M2)
  saveRDS(df.tmp, paste0("BFT.SpMan.sig.df.2021.08.16/SpMan.Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
}

#SpMan.Rsig(fq, abu,"Root", "Control", 2, 9)
#SpMan.Rsig(fq, abu,"Root", "Pre_flowering_drought", 2, 9)
#SpMan.Rsig(fq, abu,"Root", "Control", 8, 18)
#SpMan.Rsig(fq, abu,"Root", "Pre_flowering_drought", 8, 18)
#SpMan.Rsig(fq, abu,"Root", "Control", 9, 18)
#SpMan.Rsig(fq, abu,"Root", "Post_flowering_drought", 9, 18)

#SpMan.Rsig(fq, abu,"Rhizosphere", "Control", 2, 9)
#SpMan.Rsig(fq, abu,"Rhizosphere", "Pre_flowering_drought", 2, 9)
#SpMan.Rsig(fq, abu,"Rhizosphere", "Control", 8, 18)
#SpMan.Rsig(fq, abu,"Rhizosphere", "Pre_flowering_drought", 8, 18)
#SpMan.Rsig(fq, abu,"Rhizosphere", "Control", 9, 18)
#SpMan.Rsig(fq, abu,"Rhizosphere", "Post_flowering_drought", 9, 18)

#SpMan.Rsig(fq, abu,"Soil", "Control", 2, 9)
#SpMan.Rsig(fq, abu,"Soil", "Pre_flowering_drought", 2, 9)
#SpMan.Rsig(fq, abu,"Soil", "Control", 8, 18)
#SpMan.Rsig(fq, abu,"Soil", "Pre_flowering_drought", 8, 18)
#SpMan.Rsig(fq, abu,"Soil", "Control", 9, 18)
#SpMan.Rsig(fq, abu,"Soil", "Post_flowering_drought", 9, 18)


#SpMan.Rsig(fq, abu,"Leaf", "Control", 2, 9)
#SpMan.Rsig(fq, abu,"Leaf", "Pre_flowering_drought", 2, 9)
#SpMan.Rsig(fq, abu,"Leaf", "Control", 8, 18)
#SpMan.Rsig(fq, abu,"Leaf", "Pre_flowering_drought", 8, 18)
#SpMan.Rsig(fq, abu,"Leaf", "Control", 9, 18)
#SpMan.Rsig(fq, abu,"Leaf", "Post_flowering_drought", 9, 18)




library(vegan)
library(SpiecEasi)
library(psych)##
library(igraph)
#setwd("~/GaoC/R")
library(beepr)
setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")

load("Bac.Fung.data.prep.stopby8datasets.RSLZxBF.Rarefaction.2021.08.10.rdata")

habitat <- "Root"; treatment <- "Control"; tpA <- 8; tpB <- 18; type = "SpMan"; fq <- 7; abu <- 19; 
library(igraph)

####################
# Module cross BF###
####################

bac.fung.cross.module.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  modularity(fun.fc,membership(fun.fc))
  membership(fun.fc)
  print(sizes(fun.fc))###
  fun.comps <- membership(fun.fc)
  colbar <-c("#0000FF","#FF3399","#FFCC33","#9999FF", "#FF99FF", "#FFFFCC",
             "#33FFFF","#CCFF00","#CCFFCC","#FF3300","#CC99CC","#CC66CC","#FFFFCC","#CC0033","#666666","slateblue1","springgreen","steelblue1","tan1","thistle1","tomato","turquoise", "violet", "red", "yellowgreen",
             "peachpuff", "peru", "pink", "plum2", "purple","wheat", "cornsilk3","cornsilk","coral4","coral",
             "chocolate4","chocolate","black","chartreuse4","chartreuse","burlywood4","burlywood","brown4","blue","bisque4","bisque",
             "azure4","azure","aquamarine4","aquamarine","antiquewhite4","antiquewhite","aliceblue","dodgerblue4","dodgerblue","dimgrey",
             "deepskyblue4", "deepskyblue", "deeppink4", "deeppink","darkviolet", "darkslategray4","darkslategray",
             "darkseagreen4", "darkseagreen", "darksalmon", "darkred", "darkorchid4", "darkorchid", "darkorange4",
             "darkorange","firebrick","darkgreen", "darkgoldenrod4","grey", "darkgoldenrod", "darkcyan")
  V(g)$color <- colbar[fun.comps]
  
  set.seed(123)
  plot(g, edge.width=0.5,edge.color="grey", vertex.frame.color=NA,vertex.label=NA,edge.lty=1,     edge.curved=T,vertex.size=3,margin=c(0, 0,0,0)) 
}


pdf(paste0("BFT.SpMan.network.bac.fung.module.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.fung.cross.module.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.fung.cross.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.fung.cross.module.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()



#####################
# Module fung-fung###
####################

fung.module.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Eukaryote" & da0$Kingdom.1 == "Eukaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  modularity(fun.fc,membership(fun.fc))
  membership(fun.fc)
  print(sizes(fun.fc))###
  fun.comps <- membership(fun.fc)
  colbar <-c("#0000FF","#FF3399","#FFCC33","#9999FF", "#FF99FF", "#FFFFCC",
             "#33FFFF","#CCFF00","#CCFFCC","#FF3300","#CC99CC","#CC66CC","#FFFFCC","#CC0033","#666666","slateblue1","springgreen","steelblue1","tan1","thistle1","tomato","turquoise", "violet", "red", "yellowgreen",
             "peachpuff", "peru", "pink", "plum2", "purple","wheat", "cornsilk3","cornsilk","coral4","coral",
             "chocolate4","chocolate","black","chartreuse4","chartreuse","burlywood4","burlywood","brown4","blue","bisque4","bisque",
             "azure4","azure","aquamarine4","aquamarine","antiquewhite4","antiquewhite","aliceblue","dodgerblue4","dodgerblue","dimgrey",
             "deepskyblue4", "deepskyblue", "deeppink4", "deeppink","darkviolet", "darkslategray4","darkslategray",
             "darkseagreen4", "darkseagreen", "darksalmon", "darkred", "darkorchid4", "darkorchid", "darkorange4",
             "darkorange","firebrick","darkgreen", "darkgoldenrod4","grey", "darkgoldenrod", "darkcyan")
  V(g)$color <- colbar[fun.comps]
  
  set.seed(123)
  plot(g, edge.width=0.5,edge.color="grey", vertex.frame.color=NA,vertex.label=NA,edge.lty=1,     edge.curved=T,vertex.size=3,margin=c(0, 0,0,0)) 
}
pdf(paste0("BFT.SpMan.network.fung.module.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
fung.module.net("SpMan",fq, abu,"Root","Control", 2, 9)
fung.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
fung.module.net("SpMan",fq, abu,"Root","Control", 8, 18)
fung.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#fung.module.net("SpMan",fq, abu,"Root","Control", 9, 18)
#fung.module.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

fung.module.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
fung.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
fung.module.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
fung.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#fung.module.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#fung.module.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

fung.module.net("SpMan",fq, abu,"Soil","Control", 2, 9)
fung.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
fung.module.net("SpMan",fq, abu,"Soil","Control", 8, 18)
fung.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#fung.module.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#fung.module.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

fung.module.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
fung.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
fung.module.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
fung.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#fung.module.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#fung.module.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()

####################
# Module bac-bac###
####################

bac.module.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Prokaryote" & da0$Kingdom.1 == "Prokaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  modularity(fun.fc,membership(fun.fc))
  membership(fun.fc)
  print(sizes(fun.fc))###
  fun.comps <- membership(fun.fc)
  colbar <-c("#0000FF","#FF3399","#FFCC33","#9999FF", "#FF99FF", "#FFFFCC",
             "#33FFFF","#CCFF00","#CCFFCC","#FF3300","#CC99CC","#CC66CC","#FFFFCC","#CC0033","#666666","slateblue1","springgreen","steelblue1","tan1","thistle1","tomato","turquoise", "violet", "red", "yellowgreen",
             "peachpuff", "peru", "pink", "plum2", "purple","wheat", "cornsilk3","cornsilk","coral4","coral",
             "chocolate4","chocolate","black","chartreuse4","chartreuse","burlywood4","burlywood","brown4","blue","bisque4","bisque",
             "azure4","azure","aquamarine4","aquamarine","antiquewhite4","antiquewhite","aliceblue","dodgerblue4","dodgerblue","dimgrey",
             "deepskyblue4", "deepskyblue", "deeppink4", "deeppink","darkviolet", "darkslategray4","darkslategray",
             "darkseagreen4", "darkseagreen", "darksalmon", "darkred", "darkorchid4", "darkorchid", "darkorange4",
             "darkorange","firebrick","darkgreen", "darkgoldenrod4","grey", "darkgoldenrod", "darkcyan")
  V(g)$color <- colbar[fun.comps]
  
  set.seed(123)
  plot(g, edge.width=0.5,edge.color="grey", vertex.frame.color=NA,vertex.label=NA,edge.lty=1,     edge.curved=T,vertex.size=3,margin=c(0, 0,0,0)) 
}
pdf(paste0("BFT.SpMan.network.bac.module.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.module.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.module.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.module.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.module.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.module.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.module.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.module.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.module.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.module.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.module.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.module.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.module.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.module.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.module.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.module.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.module.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()


####################
# Module bac-fung inter###
####################

bac.fung.inter.module.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom != da0$Kingdom.1 ,]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  modularity(fun.fc,membership(fun.fc))
  membership(fun.fc)
  print(sizes(fun.fc))###
  fun.comps <- membership(fun.fc)
  colbar <-c("#0000FF","#FF3399","#FFCC33","#9999FF", "#FF99FF", "#FFFFCC",
             "#33FFFF","#CCFF00","#CCFFCC","#FF3300","#CC99CC","#CC66CC","#FFFFCC","#CC0033","#666666","slateblue1","springgreen","steelblue1","tan1","thistle1","tomato","turquoise", "violet", "red", "yellowgreen",
             "peachpuff", "peru", "pink", "plum2", "purple","wheat", "cornsilk3","cornsilk","coral4","coral",
             "chocolate4","chocolate","black","chartreuse4","chartreuse","burlywood4","burlywood","brown4","blue","bisque4","bisque",
             "azure4","azure","aquamarine4","aquamarine","antiquewhite4","antiquewhite","aliceblue","dodgerblue4","dodgerblue","dimgrey",
             "deepskyblue4", "deepskyblue", "deeppink4", "deeppink","darkviolet", "darkslategray4","darkslategray",
             "darkseagreen4", "darkseagreen", "darksalmon", "darkred", "darkorchid4", "darkorchid", "darkorange4",
             "darkorange","firebrick","darkgreen", "darkgoldenrod4","grey", "darkgoldenrod", "darkcyan")
  V(g)$color <- colbar[fun.comps]
  
  set.seed(123)
  plot(g, edge.width=0.5,edge.color="grey", vertex.frame.color=NA,vertex.label=NA,edge.lty=1,     edge.curved=T,vertex.size=3,margin=c(0, 0,0,0)) 
}
pdf(paste0("BFT.SpMan.network.bac.fung.inter.module.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.fung.inter.module.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.fung.inter.module.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.fung.inter.module.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()


##########
#Plotting##
###########
library(igraph)
bac.fung.cross.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  g.color$Kingdom1 <- factor(g.color$Kingdom,  labels = c("blue", "black"))
  levels(g.color$Kingdom1) = c("blue", "black") 
  V(g)$color = as.character(g.color$Kingdom1)
  
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BF-FF-BB",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.BF.BB.FF.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=3) 
}



pdf(paste0("BFT.SpMan.network.bac.fung.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.fung.cross.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.fung.cross.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.fung.cross.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.fung.cross.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.fung.cross.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.fung.cross.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.fung.cross.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.fung.cross.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()
################
##Inter-bac-Fung#
################
bac.fung.inter.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogen"] <- "purple"
  ID.tmp$color[ID.tmp$Funguild=="SaprotrophYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogenYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Saprotroph"] <- "brown"
  ID.tmp$color[ID.tmp$Funguild=="Arbuscular mycorrhizal"] <- "green"
  ID.tmp$color[ID.tmp$Funguild=="Endophyte"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Acidobacteria"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Actinobacteria"] <- "red"
  ID.tmp$color[ID.tmp$Phylum=="Bacteroidetes"] <- "black"
  ID.tmp$color[ID.tmp$Phylum=="Proteobacteria"] <- "green"
  ID.tmp$color[ID.tmp$Phylum=="Chloroflexi"] <- "brown"
  ID.tmp$color[ID.tmp$Phylum=="Firmicutes"] <- "yellow"
  ID.tmp$color[ID.tmp$Phylum=="Gemmatimonadetes"] <- "pink"
  ID.tmp$color[ID.tmp$Phylum=="Verrucomicrobia"] <- "purple"
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom != da0$Kingdom.1 ,]
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BF",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.BF.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=5) 
}

pdf(paste0("BFT.SpMan.network.inter-bac-fung.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.fung.inter.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.fung.inter.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.fung.inter.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.fung.inter.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.fung.inter.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.fung.inter.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.fung.inter.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.fung.inter.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()

##################
# Fungal network #
##################
fung.intra.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogen"] <- "purple"
  ID.tmp$color[ID.tmp$Funguild=="SaprotrophYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogenYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Saprotroph"] <- "brown"
  ID.tmp$color[ID.tmp$Funguild=="Arbuscular mycorrhizal"] <- "green"
  ID.tmp$color[ID.tmp$Funguild=="Endophyte"] <- "blue"
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Eukaryote" & da0$Kingdom.1 == "Eukaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "FF",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.FF.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=5) 
}

pdf(paste0("BFT.SpMan.network.fung.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
fung.intra.net("SpMan",fq, abu,"Root","Control", 2, 9)
fung.intra.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
fung.intra.net("SpMan",fq, abu,"Root","Control", 8, 18)
fung.intra.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#fung.intra.net("SpMan",fq, abu,"Root","Control", 9, 18)
#fung.intra.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

fung.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
fung.intra.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
fung.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
fung.intra.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#fung.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#fung.intra.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

fung.intra.net("SpMan",fq, abu,"Soil","Control", 2, 9)
fung.intra.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
fung.intra.net("SpMan",fq, abu,"Soil","Control", 8, 18)
fung.intra.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#fung.intra.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#fung.intra.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

fung.intra.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
fung.intra.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
fung.intra.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
fung.intra.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#fung.intra.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#fung.intra.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()

####################
#Bacterial network##
####################
bac.intra.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Phylum=="Acidobacteria"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Actinobacteria"] <- "red"
  ID.tmp$color[ID.tmp$Phylum=="Bacteroidetes"] <- "black"
  ID.tmp$color[ID.tmp$Phylum=="Proteobacteria"] <- "green"
  ID.tmp$color[ID.tmp$Phylum=="Chloroflexi"] <- "brown"
  ID.tmp$color[ID.tmp$Phylum=="Firmicutes"] <- "yellow"
  ID.tmp$color[ID.tmp$Phylum=="Gemmatimonadetes"] <- "pink"
  ID.tmp$color[ID.tmp$Phylum=="Verrucomicrobia"] <- "purple"
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Prokaryote" & da0$Kingdom.1 == "Prokaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BB",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.BB.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=5) 
}


pdf(paste0("BFT.SpMan.network.bac.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=9)
par(mfrow=c(4,4),mar=c(0, 0, 0, 0))
bac.intra.net("SpMan",fq, abu,"Root","Control", 2, 9)
bac.intra.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
bac.intra.net("SpMan",fq, abu,"Root","Control", 8, 18)
bac.intra.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#bac.intra.net("SpMan",fq, abu,"Root","Control", 9, 18)
#bac.intra.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

bac.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
bac.intra.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
bac.intra.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#bac.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#bac.intra.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

bac.intra.net("SpMan",fq, abu,"Soil","Control", 2, 9)
bac.intra.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
bac.intra.net("SpMan",fq, abu,"Soil","Control", 8, 18)
bac.intra.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#bac.intra.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#bac.intra.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

bac.intra.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.intra.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
bac.intra.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
bac.intra.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#bac.intra.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#bac.intra.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()


```


```{r, message=FALSE, warning=FALSE, fig.height = 10, fig.width = 6}
pdf(paste0("BFT.SpMan.network.bac.fung.select.",fq, ".", abu, ".",".2021.08.16.pdf"), width=4, height=4)
par(mfrow=c(2,2),mar=c(0, 0, 0, 0))
fung.intra.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
fung.intra.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
bac.intra.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
bac.intra.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
dev.off()
```




```{r, message=FALSE, warning=FALSE, fig.height = 10, fig.width = 6}
library(tidyverse) 
type = "SpMan"

mydir = paste0("BFT.",type,".sig.df.2021.08.16/")
da <- list.files(path=mydir, full.names=TRUE) %>% map_dfr(readRDS)

BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]

#da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
da.fung <- droplevels(da[da$Kingdom == "Eukaryote" & da$Kingdom.1 == "Eukaryote" & da$Habitat == "Rhizosphere" & da$TPA ==2,])
#da.fung$Treatment

da.fung$interaction<-"Inter-Guilds"
da.fung$interaction[da.fung$Funguild==da.fung$Funguild.1]<-"Intra-Guild"
da.fung$ab<-1


lev<-interaction(da.fung$interaction, da.fung$Treatment, da.fung$TPA, da.fung$Habitat,sep = ":") ## ccombining factors for Barplot profiling
da1<-aggregate(da.fung$ab,by=list(lev) , sum) # generate the mean for each factor level
library(splitstackshape)
dax.fung<-cSplit(da1, "Group.1", ":")
names(dax.fung)<-c("abu", "interaction","Treatment",  "tpA", "Habitat")
dax.fung$Treatment<- factor(dax.fung$Treatment, labels=c("Control", "Drought"))
#dax.fung$tpA<-factor(dax.fung$tpA, labels=c("PRE-Drought period", "PRE-Rewatering period", "POST-Drought period"))
#dax.fung$Habitat <- factor(dax.fung$Habitat, labels = c("Root", "Rhizosphere", "Soil", "Leaf"))
g1 <- ggplot(dax.fung, aes(x = Treatment, y = abu, fill= interaction)) +
  geom_bar(stat='identity', position = "fill")+
  theme_bw()+xlab("")+ylab("Proportion")+
  scale_fill_manual(values = c("purple", "pink"))+
  ggtitle("Rhizosphere: FF")+
  theme(plot.title = element_text(size = 12,face="bold",hjust=0.5),
        strip.text = element_text(size = 10,face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size=10, face="bold"),
        axis.text.y=element_text(size=10,colour="black",face="bold"),
        axis.text.x=element_text(size=10,colour="black",face="bold",angle = 45),
        axis.title=element_text(size=10,colour="black",face="bold"))+
  scale_y_continuous(labels = scales::percent)

#####
#####

da.bac <- da[da$Kingdom == "Prokaryote" & da$Kingdom.1 == "Prokaryote" & da$Habitat == "Leaf" & da$TPA ==2,]
#da.bac<-da[da$Links=="Bac-Bac",]
da.bac$interaction<-"Inter-Phyla"
da.bac$interaction[da.bac$Phylum==da.bac$Phylum.1]<-"Intra-Phylum"
da.bac$ab<-1

#str(da.bac$Phylum)

lev<-interaction(da.bac$interaction, da.bac$Treatment, da.bac$TPA, da.bac$Habitat,sep = ":") ## ccombining factors for Barplot profiling
da1<-aggregate(da.bac$ab,by=list(lev) , sum) # generate the mean for each factor level
library(splitstackshape)
dax.bac<-cSplit(da1, "Group.1", ":")
names(dax.bac)<-c("abu", "interaction","Treatment",  "tpA", "Habitat")
dax.bac$Treatment<- factor(dax.bac$Treatment, labels=c("Control", "Drought"))
#dax.bac$tpA<-factor(dax.bac$tpA, labels=c("PRE-Drought period", "PRE-Rewatering period", "POST-Drought period"))
g2 <- ggplot(dax.bac, aes(x = Treatment, y = abu, fill= interaction)) +
  geom_bar(stat='identity', position = "fill")+
  theme_bw()+xlab("")+ylab("Proportion")+
  scale_fill_manual(values = c("purple", "pink"))+
  ggtitle("Leaf: BB")+
  theme(plot.title = element_text(size = 12,face="bold",hjust=0.5),
        strip.text = element_text(size = 10,face="bold"),
        legend.title = element_blank(),
        legend.text = element_text(colour="black", size=10, face="bold"),
        axis.text.y=element_text(size=10,colour="black",face="bold"),
        axis.text.x=element_text(size=10,colour="black",face="bold",angle = 45),
        axis.title=element_text(size=10,colour="black",face="bold"))+
  scale_y_continuous(labels = scales::percent)



pdf("BFT.bac.fung.phylum.guild.2021.09.03.pdf", width = 3, height = 5) # Open a new pdf file
library(gridExtra)
grid.arrange(g1,g2)
dev.off() 
```


```{r, message=FALSE, warning=FALSE, fig.height = 7, fig.width = 9}
##########
#amf/Namf#
##########
library(igraph)
#habitat <- "Root"; treatment <- "Control"; tpA <- 8; tpB <- 18; type = "SpMan"
amf.Namf.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogen"] <- "purple"
  ID.tmp$color[ID.tmp$Funguild=="SaprotrophYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogenYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Saprotroph"] <- "brown"
  ID.tmp$color[ID.tmp$Funguild=="Arbuscular mycorrhizal"] <- "skyblue"
  ID.tmp$color[ID.tmp$Funguild=="Endophyte"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Acidobacteria"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Actinobacteria"] <- "red"
  ID.tmp$color[ID.tmp$Phylum=="Bacteroidetes"] <- "black"
  ID.tmp$color[ID.tmp$Phylum=="Proteobacteria"] <- "green"
  ID.tmp$color[ID.tmp$Phylum=="Chloroflexi"] <- "brown"
  ID.tmp$color[ID.tmp$Phylum=="Firmicutes"] <- "yellow"
  ID.tmp$color[ID.tmp$Phylum=="Gemmatimonadetes"] <- "pink"
  ID.tmp$color[ID.tmp$Phylum=="Verrucomicrobia"] <- "purple"
  
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <-da0[da0$Funguild == "Arbuscular mycorrhizal" | da0$Funguild.1 == "Arbuscular mycorrhizal", ]
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BF",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.amf.Namf.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=5) 
}

pdf(paste0("BFT.SpMan.network.amf.Namf.",fq, ".", abu, ".",".2021.08.16.pdf"), width=9, height=7)
par(mfrow=c(3,4),mar=c(0, 0, 0, 0))
amf.Namf.net("SpMan",fq, abu,"Root","Control", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Root","Control", 8, 18)
amf.Namf.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)
#amf.Namf.net("SpMan",fq, abu,"Root","Control", 9, 18)
#amf.Namf.net("SpMan",fq, abu,"Root","Post_flowering_drought", 9, 18)

amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)
#amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Control", 9, 18)
#amf.Namf.net("SpMan",fq, abu,"Rhizosphere","Post_flowering_drought", 9, 18)

amf.Namf.net("SpMan",fq, abu,"Soil","Control", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
amf.Namf.net("SpMan",fq, abu,"Soil","Control", 8, 18)
amf.Namf.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)
#amf.Namf.net("SpMan",fq, abu,"Soil","Control", 9, 18)
#amf.Namf.net("SpMan",fq, abu,"Soil","Post_flowering_drought", 9, 18)

#amf.Namf.net("SpMan",fq, abu,"Leaf","Control", 2, 9)
#amf.Namf.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 2, 9)
#amf.Namf.net("SpMan",fq, abu,"Leaf","Control", 8, 18)
#amf.Namf.net("SpMan",fq, abu,"Leaf","Pre_flowering_drought", 8, 18)
#amf.Namf.net("SpMan",fq, abu,"Leaf","Control", 9, 18)
#amf.Namf.net("SpMan",fq, abu,"Leaf","Post_flowering_drought", 9, 18)
dev.off()

##########
#amf/Namf#
##########
library(igraph)
habitat <- "Root"; treatment <- "Control"; tpA <- 8; tpB <- 18; type = "SpMan"
amf.Namf.Fungi.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogen"] <- "purple"
  ID.tmp$color[ID.tmp$Funguild=="SaprotrophYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogenYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Saprotroph"] <- "brown"
  ID.tmp$color[ID.tmp$Funguild=="Arbuscular mycorrhizal"] <- "skyblue"
  ID.tmp$color[ID.tmp$Funguild=="Endophyte"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Acidobacteria"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Actinobacteria"] <- "red"
  ID.tmp$color[ID.tmp$Phylum=="Bacteroidetes"] <- "black"
  ID.tmp$color[ID.tmp$Phylum=="Proteobacteria"] <- "green"
  ID.tmp$color[ID.tmp$Phylum=="Chloroflexi"] <- "brown"
  ID.tmp$color[ID.tmp$Phylum=="Firmicutes"] <- "yellow"
  ID.tmp$color[ID.tmp$Phylum=="Gemmatimonadetes"] <- "pink"
  ID.tmp$color[ID.tmp$Phylum=="Verrucomicrobia"] <- "purple"
  
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  
  da <-da0[(da0$Funguild == "Arbuscular mycorrhizal" & da0$Kingdom.1 =="Eukaryote" &da0$Funguild.1 != "Arbuscular mycorrhizal" ) 
           
           | (da0$Funguild.1 == "Arbuscular mycorrhizal" && da0$Kingdom =="Eukaryote" &da0$Funguild != "Arbuscular mycorrhizal" ), ]
  

  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BF",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.amf.Namf.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=3,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=10) 
}

pdf(paste0("BFT.SpMan.network.amf.Namf.Fungi.",fq, ".", abu, ".",".2021.11.11.pdf"), width=9, height=7)
par(mfrow=c(3,4),mar=c(2, 2, 2, 2))
amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Control", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Control", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Control", 2, 9)
#amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
#amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Control", 8, 18)
amf.Namf.Fungi.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)

amf.Namf.Fungi.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
amf.Namf.Fungi.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)

amf.Namf.Fungi.net("SpMan",fq, abu,"Soil","Control", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Soil","Control", 2, 9)
#amf.Namf.Fungi.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
amf.Namf.Fungi.net("SpMan",fq, abu,"Soil","Control", 8, 18)
amf.Namf.Fungi.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)

dev.off()

##########
#amf/Bacteria#
##########
library(igraph)
habitat <- "Root"; treatment <- "Control"; tpA <- 8; tpB <- 18; type = "SpMan"
amf.Bacteria.net<-function(type,fq, abu, habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  ID.tmp$shape <- "circle"; ID.tmp$shape[ID.tmp$Kingdom=="Eukaryote"]<-"square"
  ID.tmp$color <- "grey"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogen"] <- "purple"
  ID.tmp$color[ID.tmp$Funguild=="SaprotrophYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Plant pathogenYeast"] <- "red"
  ID.tmp$color[ID.tmp$Funguild=="Saprotroph"] <- "brown"
  ID.tmp$color[ID.tmp$Funguild=="Arbuscular mycorrhizal"] <- "skyblue"
  ID.tmp$color[ID.tmp$Funguild=="Endophyte"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Acidobacteria"] <- "blue"
  ID.tmp$color[ID.tmp$Phylum=="Actinobacteria"] <- "red"
  ID.tmp$color[ID.tmp$Phylum=="Bacteroidetes"] <- "black"
  ID.tmp$color[ID.tmp$Phylum=="Proteobacteria"] <- "green"
  ID.tmp$color[ID.tmp$Phylum=="Chloroflexi"] <- "brown"
  ID.tmp$color[ID.tmp$Phylum=="Firmicutes"] <- "yellow"
  ID.tmp$color[ID.tmp$Phylum=="Gemmatimonadetes"] <- "pink"
  ID.tmp$color[ID.tmp$Phylum=="Verrucomicrobia"] <- "purple"
  
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  
  da <-da0[(da0$Funguild == "Arbuscular mycorrhizal" & da0$Kingdom.1 =="Prokaryote" ) 
           
           | (da0$Funguild.1 == "Arbuscular mycorrhizal" & da0$Kingdom =="Prokaryote"  ), ]
  
  
  g <- graph.data.frame(da, directed=FALSE)
  g.color = droplevels(ID.tmp[ID.tmp$OTU.ID %in% V(g)$name,])
  g.color<-g.color[match(V(g)$name, g.color$OTU.ID),]
  #levels(g.color$Kingdom) = c("blue", "black") 
  V(g)$color = as.character(g.color$color)
  V(g)$shape <-as.character(g.color$shape)
  # network property
  # 边数量 The size of the graph (number of edges)
  num.edges = length(E(g)) # length(curve_multiple(g))
  #print(num.edges)
  # 顶点数量 Order (number of vertices) of a graph
  num.vertices = length(V(g))# length(diversity(g, weights = NULL, vids = V(g)))
  #print(num.vertices)
  # 连接数(connectance) 网络中物种之间实际发生的相互作用数之和（连接数之和）占总的潜在相互作用数（连接数）的比例，可以反映网络的复杂程度
  connectance = edge_density(g,loops=FALSE)# 同 graph.density;loops如果为TRUE,允许自身环（self loops即A--A或B--B）的存在
  #print(connectance)
  # 平均度(Average degree)
  average.degree = mean(igraph::degree(g))# 或者为2M/N,其中M 和N 分别表示网络的边数和节点数。
  #print(average.degree)
  # 平均路径长度(Average path length)
  average.path.length = average.path.length(g) # 同mean_distance(g) # mean_distance calculates the average path length in a graph
  #print(average.path.length)
  # 直径(Diameter)
  diameter = diameter(g, directed = FALSE, unconnected = TRUE, weights = NULL)
  #print(diameter)
  # 群连通度 edge connectivity / group adhesion
  edge.connectivity = edge_connectivity(g)
  #print(edge.connectivity)
  # 聚集系数(Clustering coefficient)：分局域聚类系数和全局聚集系数，是反映网络中节点的紧密关系的参数，也称为传递性。整个网络的全局聚集系数C表征了整个网络的平均的“成簇性质”。
  clustering.coefficient = transitivity(g) 
  #print(clustering.coefficient)
  no.clusters = no.clusters(g)
  #print(no.clusters)
  # 介数中心性(Betweenness centralization)
  centralization.betweenness = centralization.betweenness(g)$centralization 
  #print(centralization.betweenness)
  # 度中心性(Degree centralization)
  centralization.degree = centralization.degree(g)$centralization
  #print(centralization.degree)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #print(modularity(fun.fc))## 模块性大于0.45，说明网络有效##
  Modularity<-modularity(fun.fc,membership(fun.fc))
  #membership(fun.fc)
  No.modules<-nrow(data.frame(sizes(fun.fc)))
  
  df.tmp<-data.frame(network = "BF",type, habitat, treatment, tpA, tpB,  num.edges, num.vertices, connectance, average.degree, average.path.length, diameter, edge.connectivity, clustering.coefficient,
                     no.clusters, centralization.betweenness,centralization.degree,  Modularity, No.modules)
  saveRDS(df.tmp, paste0("SpMan.network.property.2021.09.01/SpMan.network.property.amf.Bacteria.",type,".",habitat, ".", treatment,".",tpA,".",tpB,".RDS"))
  
  # Edge property: assign postive/negative edges into solid(lty=1)/dash(lty=3) lines
  g.E <-data.frame(get.edgelist(g))
  names(g.E)<- c("V1", "V2")
  
  #Edge property: assign intraBacteria/intraFungi/interBacteriaFungi edges into skyblue, grey and red colors
  V1<-data.frame("v1"=g.E$V1)
  V2<-data.frame("v2"=g.E$V2)
  
  ID.tmpx<-ID.tmp[,c("OTU.ID", "Kingdom")]
  IDsub1<-ID.tmpx[ID.tmpx$OTU.ID %in% V1$v1, ]
  IDsub2<-ID.tmpx[ID.tmpx$OTU.ID %in% V2$v2, ]
  V1$id  <- 1:nrow(V1); V2$id  <- 1:nrow(V2)
  M1<-merge(V1, IDsub1, by.x = "v1", by.y = "OTU.ID", all.x= T); M1<-M1[order(M1$id), ]
  M2<-merge(V2, IDsub2, by.x = "v2", by.y = "OTU.ID", all.x = T); M2<-M2[order(M2$id), ]
  
  M1$BF<-"red"
  M1$BF[M1$Kingdom=="Prokaryote" & M2$Kingdom=="Prokaryote" ]<-"grey"
  M1$BF[M1$Kingdom=="Eukaryote" & M2$Kingdom=="Eukaryote" ]<-"skyblue"
  
  E(g)$color = as.character(M1$BF)
  
  set.seed(123)
  plot(g, edge.width=1.5,  vertex.frame.color=NA,vertex.label=NA,edge.lty=1, edge.curved=T,vertex.size=10) 
}

pdf(paste0("BFT.SpMan.network.amf.Bacteria.",fq, ".", abu, ".",".2021.11.11.pdf"), width=9, height=7)
par(mfrow=c(3,4),mar=c(2, 2, 2, 2))
amf.Bacteria.net("SpMan",fq, abu,"Root","Control", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Root","Control", 2, 9)
#amf.Bacteria.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Root","Control", 8, 18)
amf.Bacteria.net("SpMan",fq, abu,"Root","Pre_flowering_drought", 8, 18)

amf.Bacteria.net("SpMan",fq, abu,"Rhizosphere","Control", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Rhizosphere","Control", 8, 18)
amf.Bacteria.net("SpMan",fq, abu,"Rhizosphere","Pre_flowering_drought", 8, 18)

amf.Bacteria.net("SpMan",fq, abu,"Soil","Control", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 2, 9)
amf.Bacteria.net("SpMan",fq, abu,"Soil","Control", 8, 18)
amf.Bacteria.net("SpMan",fq, abu,"Soil","Pre_flowering_drought", 8, 18)

dev.off()
```



```{r, message=FALSE, warning=FALSE, fig.height = 3, fig.width = 6}
##################
#Network property#
##################
library(tidyverse) 
mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.network.property.2021.09.01"
da0 <- list.files(path=mydir, full.names=TRUE) %>% map_dfr(readRDS)
#da0 <- da0[da0$network!= "BF-FF-BB",]
da <- da0[ !c(da0$habitat == "Leaf" & da0$network %in% c("BF","FF","BF-FF-BB") &da0$tpA == 2),]

da$Treatment2<-da$treatment
da$tpA <- factor(da$tpA, labels = c("Drought period", "Rewetting period"))
da$habitat <-factor(da$habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
da$network <- factor(da$network, labels = c("B-B", "CrossBF", "B-F", "F-F"))
da$network <- factor(da$network, levels = c("CrossBF", "B-B",  "B-F", "F-F"))
ggplot(da, aes(x= as.numeric(Treatment2),y= log(num.edges+1), color  = network )) + 
  geom_smooth(method='lm', size =1, se = FALSE)+
  scale_color_manual(values = c("black", "blue","red", "cyan", "brown", "yellow"))+
  scale_linetype_manual(values = c(3, 1, 2))+
  xlab("")+ylab("Log (Number of edges + 1)")+theme_bw()+
  guides(fill=guide_legend(title= "Type"))+
  facet_grid(habitat~tpA)+
  scale_x_continuous(breaks = c(1, 2),labels = c("Control", "Stress"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.x=element_text(colour="black",size=8,face="bold",angle = 90, hjust = 1),
        axis.text.y=element_text(colour="black",size=8,face="bold"),
        axis.title=element_text(colour="black",size=8 ,face="bold"))
ggsave("SpMan.BFT.bac.fung.No.edges.CK.Stress.2021.09.01.pdf", width = 4, height = 6)


ggplot(da, aes(x= as.numeric(Treatment2),y= log(num.vertices+1), color  = network )) + 
  geom_smooth(method='lm', size =1, se = FALSE)+
  scale_color_manual(values = c("black", "blue","red", "cyan", "brown", "yellow"))+
  scale_linetype_manual(values = c(3, 1, 2))+
  xlab("")+ylab("Log (Number of vertices + 1)")+theme_bw()+
  guides(fill=guide_legend(title= "Type"))+
  facet_grid(habitat~tpA)+
  scale_x_continuous(breaks = c(1, 2),labels = c("Control", "Stress"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.x=element_text(colour="black",size=8,face="bold",angle = 90, hjust = 1),
        axis.text.y=element_text(colour="black",size=8,face="bold"),
        axis.title=element_text(colour="black",size=8 ,face="bold"))
ggsave("SpMan.BFT.bac.fung.No.vertices.CK.Stress.2021.09.01.pdf", width = 4, height = 6)

ggplot(da, aes(x= as.numeric(Treatment2),y= Modularity, color  = network )) + 
  geom_smooth(method='lm', size =1, se = FALSE)+
  scale_color_manual(values = c("black", "blue","red", "cyan", "brown", "yellow"))+
  scale_linetype_manual(values = c(3, 1, 2))+
  xlab("")+ylab("Modularity")+theme_bw()+
  guides(fill=guide_legend(title= "Type"))+
  facet_grid(habitat~tpA)+
  scale_x_continuous(breaks = c(1, 2),labels = c("Control", "Stress"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.x=element_text(colour="black",size=8,face="bold",angle = 90, hjust = 1),
        axis.text.y=element_text(colour="black",size=8,face="bold"),
        axis.title=element_text(colour="black",size=8 ,face="bold"))
ggsave("SpMan.BFT.bac.fung.Modularity.CK.Stress.2021.09.01.pdf", width = 4, height = 6)


```


###ZiPi

```{r, message=FALSE, warning=FALSE, fig.height = 6, fig.width = 6}
rm(list=ls())
library(vegan)
library(SpiecEasi)
library(psych)##
library(igraph)
#setwd("~/GaoC/R")
library(beepr)
setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")
habitat <- "Root"; treatment <- "Control"; tpA <- 8; tpB <- 18; type = "SpMan"; fq= 7; abu = 19

library(igraph)
library(brainGraph)##
ZiPiBF<-function(habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  g <- graph.data.frame(da, directed=FALSE)
  
  #g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #modularity(fun.fc)##0.785,模块性大于0.45，说明网络有效##
  modu<-membership(fun.fc)
  otu.name<-names(modu)
  membership1<-data.frame(cbind(otu.name,modu))
  
  ###Calculate vertex participation coefficient
  Pi<-part_coeff(g, modu)
  ###Calculate vertex within-module degree z-score
  Zi<-within_module_deg_z_score(g, modu)
  
  Pi.cutoff=0.62
  Zi.cutoff=2.5
  
  PiZi<-data.frame(cbind(Pi, Zi))
  PiZi$group<-factor(ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi >Zi.cutoff, "Network hub",
                            ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi <=Zi.cutoff, "Connector", ifelse(PiZi$Pi<= Pi.cutoff & PiZi$Zi >Zi.cutoff, "Module hub", "Peripherals") )))
  PiZi$otu.name <- row.names(PiZi)   
  ID.tmp1<-ID.tmp[row.names(ID.tmp) %in% row.names(PiZi),]
  ID.tmp1<-ID.tmp1[match(PiZi$otu.name, ID.tmp1$OTU.ID),]
  ID.tmp1$OTU.ID == PiZi$otu.name
  PiZi<-data.frame(PiZi, ID.tmp1)
  
  PiZi$Habitat <-habitat
  PiZi$Treatment <-treatment
  PiZi$tpA<-tpA
  PiZi$tpB<-tpB
  PiZi$network <- "crossBF"
  write.csv(PiZi, paste0("SpMan.cross.BF.ZiPi/PiZi.crossBF.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  #########
  ###interBF
  #########
  
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom != da0$Kingdom.1 ,]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #modularity(fun.fc)##0.785,模块性大于0.45，说明网络有效##
  modu<-membership(fun.fc)
  otu.name<-names(modu)
  membership1<-data.frame(cbind(otu.name,modu))
  
  ###Calculate vertex participation coefficient
  Pi<-part_coeff(g, modu)
  ###Calculate vertex within-module degree z-score
  Zi<-within_module_deg_z_score(g, modu)
  
  Pi.cutoff=0.62
  Zi.cutoff=2.5
  
  PiZi<-data.frame(cbind(Pi, Zi))
  PiZi$group<-factor(ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi >Zi.cutoff, "Network hub",
                            ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi <=Zi.cutoff, "Connector", ifelse(PiZi$Pi<= Pi.cutoff & PiZi$Zi >Zi.cutoff, "Module hub", "Peripherals") )))
  PiZi$otu.name <- row.names(PiZi)   
  ID.tmp1<-ID.tmp[row.names(ID.tmp) %in% row.names(PiZi),]
  ID.tmp1<-ID.tmp1[match(PiZi$otu.name, ID.tmp1$OTU.ID),]
  ID.tmp1$OTU.ID == PiZi$otu.name
  PiZi<-data.frame(PiZi, ID.tmp1)
  
  PiZi$Habitat <-habitat
  PiZi$Treatment <-treatment
  PiZi$tpA<-tpA
  PiZi$tpB<-tpB
  PiZi$network <- "interBF"
  write.csv(PiZi, paste0("SpMan.cross.BF.ZiPi/PiZi.interBF.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  #########
  ###Fung-Fung
  #########
  
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Eukaryote" & da0$Kingdom.1 == "Eukaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #modularity(fun.fc)##0.785,模块性大于0.45，说明网络有效##
  modu<-membership(fun.fc)
  otu.name<-names(modu)
  membership1<-data.frame(cbind(otu.name,modu))
  
  ###Calculate vertex participation coefficient
  Pi<-part_coeff(g, modu)
  ###Calculate vertex within-module degree z-score
  Zi<-within_module_deg_z_score(g, modu)
  
  Pi.cutoff=0.62
  Zi.cutoff=2.5
  
  PiZi<-data.frame(cbind(Pi, Zi))
  PiZi$group<-factor(ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi >Zi.cutoff, "Network hub",
                            ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi <=Zi.cutoff, "Connector", ifelse(PiZi$Pi<= Pi.cutoff & PiZi$Zi >Zi.cutoff, "Module hub", "Peripherals") )))
  PiZi$otu.name <- row.names(PiZi)   
  ID.tmp1<-ID.tmp[row.names(ID.tmp) %in% row.names(PiZi),]
  ID.tmp1<-ID.tmp1[match(PiZi$otu.name, ID.tmp1$OTU.ID),]
  ID.tmp1$OTU.ID == PiZi$otu.name
  PiZi<-data.frame(PiZi, ID.tmp1)
  
  PiZi$Habitat <-habitat
  PiZi$Treatment <-treatment
  PiZi$tpA<-tpA
  PiZi$tpB<-tpB
  PiZi$network <- "Fung-Fung"
  write.csv(PiZi, paste0("SpMan.cross.BF.ZiPi/PiZi.fung.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  #########
  ###Fung-Fung
  #########
  
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Prokaryote" & da0$Kingdom.1 == "Prokaryote",]
  
  g <- graph.data.frame(da, directed=FALSE)
  
  fun.fc<-cluster_fast_greedy(g)##针对无方向graph
  #modularity(fun.fc)##0.785,模块性大于0.45，说明网络有效##
  modu<-membership(fun.fc)
  otu.name<-names(modu)
  membership1<-data.frame(cbind(otu.name,modu))
  
  ###Calculate vertex participation coefficient
  Pi<-part_coeff(g, modu)
  ###Calculate vertex within-module degree z-score
  Zi<-within_module_deg_z_score(g, modu)
  
  Pi.cutoff=0.62
  Zi.cutoff=2.5
  
  PiZi<-data.frame(cbind(Pi, Zi))
  PiZi$group<-factor(ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi >Zi.cutoff, "Network hub",
                            ifelse(PiZi$Pi> Pi.cutoff & PiZi$Zi <=Zi.cutoff, "Connector", ifelse(PiZi$Pi<= Pi.cutoff & PiZi$Zi >Zi.cutoff, "Module hub", "Peripherals") )))
  PiZi$otu.name <- row.names(PiZi)   
  ID.tmp1<-ID.tmp[row.names(ID.tmp) %in% row.names(PiZi),]
  ID.tmp1<-ID.tmp1[match(PiZi$otu.name, ID.tmp1$OTU.ID),]
  ID.tmp1$OTU.ID == PiZi$otu.name
  PiZi<-data.frame(PiZi, ID.tmp1)
  
  PiZi$Habitat <-habitat
  PiZi$Treatment <-treatment
  PiZi$tpA<-tpA
  PiZi$tpB<-tpB
  PiZi$network <- "Bac-Bac"
  write.csv(PiZi, paste0("SpMan.cross.BF.ZiPi/PiZi.bac.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
}

#ZiPiBF("Root","Control", 2, 9)
#ZiPiBF("Root","Pre_flowering_drought", 2, 9)
#ZiPiBF("Root","Control", 8, 18)
#ZiPiBF("Root","Pre_flowering_drought", 8, 18)
#ZiPiBF("Root","Control", 9, 18)
#ZiPiBF("Root","Post_flowering_drought", 9, 18)

#ZiPiBF("Rhizosphere","Control", 2, 9)
#ZiPiBF("Rhizosphere","Pre_flowering_drought", 2, 9)
#ZiPiBF("Rhizosphere","Control", 8, 18)
#ZiPiBF("Rhizosphere","Pre_flowering_drought", 8, 18)
#ZiPiBF("Rhizosphere","Control", 9, 18)
#ZiPiBF("Rhizosphere","Post_flowering_drought", 9, 18)


#ZiPiBF("Soil","Control", 2, 9)
#ZiPiBF("Soil","Pre_flowering_drought", 2, 9)
#ZiPiBF("Soil","Control", 8, 18)
#ZiPiBF("Soil","Pre_flowering_drought", 8, 18)
#ZiPiBF("Soil","Control", 9, 18)
#ZiPiBF("Soil","Post_flowering_drought", 9, 18)

#ZiPiBF("Leaf","Control", 2, 9)
#ZiPiBF("Leaf","Pre_flowering_drought", 2, 9)
#ZiPiBF("Leaf","Control", 8, 18)
#ZiPiBF("Leaf","Pre_flowering_drought", 8, 18)
#ZiPiBF("Leaf","Control", 9, 18)
#ZiPiBF("Leaf","Post_flowering_drought", 9, 18)

library(beepr)
beep()


library(plyr) 
library(tidyverse) 
mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.cross.BF.ZiPi"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)

PiZi0 = ldply(myfiles, read_csv)
Pi.cutoff=0.62
Zi.cutoff=2.5

PiZi <- PiZi0[PiZi0$network == "crossBF",]
PiZi <- PiZi[PiZi$tpA!= 9,]

#PiZi$tpA

PiZi <- droplevels(PiZi[!(PiZi$Habitat=="Leaf" & PiZi$tpA == 2),])

PiZi$Habitat<-factor(PiZi$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
PiZi$Treatment1<-factor(PiZi$tpA, labels = c("Drought period", "Rewetting period"))
PiZi$Treatment2<-factor(PiZi$Treatment, labels = c("Control", "Drought"))
PiZi$Kingdom2 <- factor (PiZi$Kingdom, labels = c("Fungi", "Bacteria"))
PiZi$Treatment3 <- interaction (PiZi$Treatment1, PiZi$Treatment2)
PiZi$Treatment3 <- factor(PiZi$Treatment3 , labels = c("Control", "Control", "Drought", "Rewetting"))
ggplot(PiZi, aes(x=Pi, y=Zi, shape = Kingdom2, color = Treatment3)) +
  geom_point(size=2, alpha = 0.3)+theme_bw()+facet_grid(Habitat~Treatment1)+xlim(0,1)+
  scale_shape_manual(values=c(17, 16))+
  geom_vline(xintercept = Pi.cutoff, color = "blue", linetype = 3)+
  geom_hline(yintercept = Zi.cutoff, color = "blue", linetype = 3)+
  scale_color_manual(values = c( "black","red", "blue"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.y=element_text(size=8,face="bold"),
        axis.text.x=element_text(size=8,face="bold",angle = 45),
        axis.title=element_text(size=8,face="bold"))
ggsave("crossBF.ZiPi.2021.09.03.pdf", width = 6, height = 6)

data<-droplevels(subset(PiZi, Pi > Pi.cutoff | Zi > Zi.cutoff ))
write.csv(data,"crossBF.ZiPi.keystone.2021.09.03.csv")

data<-read.csv("crossBF.ZiPi.keystone.2021.09.03.csv", head =T)
data$abu <-1
library(splitstackshape)
data1<-data[,c("Treatment", "Phylum","Funguild", "abu","Habitat", "Treatment1" )]

data1$fact<-paste(data1$Treatment, data1$Phylum, data1$Funguild, data1$Habitat, data1$Treatment1, sep=".")
data.agg<-aggregate(data1$abu, by=list(Occurence=data1$fact), FUN=sum)
data.agg1<-cSplit(data.agg, "Occurence", ".")
names(data.agg1) <- c("Occurence", "Treatment", "Phylum", "Funguild","Habitat", "Treatment1")

data.agg1<-droplevels(data.agg1[data.agg1$Phylum!="X_" & data.agg1$Phylum!="Other" & data.agg1$Phylum!="_" ,  ])
data.agg1$fac <- paste(data.agg1$Treatment,  data.agg1$Habitat, data.agg1$Treatment1, sep=".")

#data.agg1$Phylum
library(reshape2)
data_wide <- dcast(data.agg1,  Phylum ~fac, value.var="Occurence")
data_wide[is.na(data_wide)] = 0

row.names(data_wide)<-data_wide$Phylum
data_wide<-data_wide[,-1]
data_wide <- data_wide[order(-rowSums(data_wide)),]
row.names(data_wide)
fung.L.lev<-data.frame(t(data_wide))
dax<-data.frame(var=row.names(fung.L.lev))
dax<-cSplit(dax, "var", ".")
names(dax)<-c( "Treatment", "Habitat", "Treatment1")

fung.L.lev<-cbind(Group.1=row.names(fung.L.lev),fung.L.lev )

fung.L1<-fung.L.lev[,c(1,2:12)] # the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ".")
names(fung.L1)<-c("Phylum","Keystone", "Treatment", "Habitat", "Treatment1")

fung.L2<-fung.L.lev[,c(1,13:ncol(fung.L.lev))]  # the domiant OTUs
fung.L2 <- melt(fung.L2,id.vars = "Group.1")
fung.L2<-cSplit(fung.L2, "Group.1", ".")
names(fung.L2)<-c("Phylum","Keystone", "Treatment", "Habitat", "Treatment1")
fung.L2$Phylum<-"Other"


data.agg1<-rbind(fung.L1, fung.L2)
col11<-c("darkblue","red","#ff00ff", "deepskyblue", "gold", "blue", "navy", "darkgreen","black", "orange", "purple", "grey")

data.agg1$Habitat <- factor(data.agg1$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
data.agg1$Treatment <-factor(data.agg1$Treatment, labels = c("Con", "Str"))
data.agg1$Treatment1<-factor(data.agg1$Treatment1, levels = c("Drought period", "Rewetting period"))

data.agg1$Treatment3 <- interaction (data.agg1$Treatment, data.agg1$Treatment1)
data.agg1$Treatment3  <- factor(data.agg1$Treatment3  , labels = c("Control","Drought", "Control",  "Rewetting"))
ggplot(data.agg1, aes(x = Treatment3, y = Keystone, fill=Phylum)) +
    geom_bar(stat='identity') + #, position = "fill"
    labs(x="",y = "No. of keystone OTUs")+
    facet_grid(Habitat~Treatment1, scales="free_x")+
    theme_bw()+  scale_fill_manual(values= col11)+
    theme(strip.text = element_text(size = 8,face="bold"),
          panel.spacing = unit(0, "lines"),
          legend.title = element_text(colour="black", size=8, face="bold"),
          legend.text = element_text(colour="black", size=8, face="bold"),
          axis.text.y=element_text(size=8,face="bold"),
          axis.text.x=element_text(size=8,face="bold"),
          axis.title=element_text(size=8,face="bold"))
ggsave("ZiPi.crossBF.KeystoneTaxa.2021.09.03.pdf", width = 6, height = 6)



##########
#interBF##
##########
library(plyr) 
library(tidyverse) 
mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.cross.BF.ZiPi"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)

PiZi0 = ldply(myfiles, read_csv)
Pi.cutoff=0.62
Zi.cutoff=2.5

PiZi <- PiZi0[PiZi0$network == "interBF",]
PiZi <- PiZi[PiZi$tpA!= 9,]

#PiZi$tpA

PiZi <- droplevels(PiZi[!(PiZi$Habitat=="Leaf" & PiZi$tpA == 2),])

PiZi$Habitat<-factor(PiZi$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
PiZi$Treatment1<-factor(PiZi$tpA, labels = c("Drought period", "Rewetting period"))
PiZi$Treatment2<-factor(PiZi$Treatment, labels = c("Control", "Drought"))
PiZi$Kingdom2 <- factor (PiZi$Kingdom, labels = c("Fungi", "Bacteria"))
PiZi$Treatment3 <- interaction (PiZi$Treatment1, PiZi$Treatment2)
PiZi$Treatment3 <- factor(PiZi$Treatment3 , labels = c("Control", "Control", "Drought", "Rewetting"))

ggplot(PiZi, aes(x=Pi, y=Zi, shape = Kingdom2,  color = Treatment3)) +
  geom_point(size=2, alpha = 0.3)+theme_bw()+facet_grid(Habitat~Treatment1)+xlim(0,1)+
  scale_shape_manual(values=c(17, 16))+
  geom_vline(xintercept = Pi.cutoff, color = "blue", linetype = 3)+
  geom_hline(yintercept = Zi.cutoff, color = "blue", linetype = 3)+
  scale_color_manual(values = c( "black","red", "blue"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.y=element_text(size=8,face="bold"),
        axis.text.x=element_text(size=8,face="bold",angle = 45),
        axis.title=element_text(size=8,face="bold"))
ggsave("interBF.ZiPi.2021.09.03.pdf", width = 6, height = 6)

data<-droplevels(subset(PiZi, Pi > Pi.cutoff | Zi > Zi.cutoff ))
write.csv(data,"interBF.ZiPi.keystone.2021.09.03.csv")

data<-read.csv("interBF.ZiPi.keystone.2021.09.03.csv", head =T)
data$abu <-1
library(splitstackshape)
data1<-data[,c("Treatment", "Phylum","Funguild", "abu","Habitat", "Treatment1" )]

data1$fact<-paste(data1$Treatment, data1$Phylum, data1$Funguild, data1$Habitat, data1$Treatment1, sep=".")
data.agg<-aggregate(data1$abu, by=list(Occurence=data1$fact), FUN=sum)
data.agg1<-cSplit(data.agg, "Occurence", ".")
names(data.agg1) <- c("Occurence", "Treatment", "Phylum", "Funguild","Habitat", "Treatment1")

data.agg1<-droplevels(data.agg1[data.agg1$Phylum!="X_" & data.agg1$Phylum!="Other" & data.agg1$Phylum!="_" ,  ])
data.agg1$fac <- paste(data.agg1$Treatment,  data.agg1$Habitat, data.agg1$Treatment1, sep=".")

#data.agg1$Phylum
library(reshape2)
data_wide <- dcast(data.agg1,  Phylum ~fac, value.var="Occurence")
data_wide[is.na(data_wide)] = 0

row.names(data_wide)<-data_wide$Phylum
data_wide<-data_wide[,-1]
data_wide <- data_wide[order(-rowSums(data_wide)),]
row.names(data_wide)
fung.L.lev<-data.frame(t(data_wide))
dax<-data.frame(var=row.names(fung.L.lev))
dax<-cSplit(dax, "var", ".")
names(dax)<-c( "Treatment", "Habitat", "Treatment1")

fung.L.lev<-cbind(Group.1=row.names(fung.L.lev),fung.L.lev )

fung.L1<-fung.L.lev[,c(1,2:12)] # the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ".")
names(fung.L1)<-c("Phylum","Keystone", "Treatment", "Habitat", "Treatment1")

fung.L2<-fung.L.lev[,c(1,13:ncol(fung.L.lev))]  # the domiant OTUs
fung.L2 <- melt(fung.L2,id.vars = "Group.1")
fung.L2<-cSplit(fung.L2, "Group.1", ".")
names(fung.L2)<-c("Phylum","Keystone", "Treatment", "Habitat", "Treatment1")
fung.L2$Phylum<-"Other"


data.agg1<-rbind(fung.L1, fung.L2)
col11<-c("darkblue","red","#ff00ff", "deepskyblue", "gold", "blue", "navy", "darkgreen","black", "orange", "purple", "grey")

data.agg1$Habitat <- factor(data.agg1$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
data.agg1$Treatment <-factor(data.agg1$Treatment, labels = c("Con", "Str"))
data.agg1$Treatment1<-factor(data.agg1$Treatment1, levels = c("Drought period", "Rewetting period"))

data.agg1$Treatment3 <- interaction (data.agg1$Treatment, data.agg1$Treatment1)
data.agg1$Treatment3  <- factor(data.agg1$Treatment3  , labels = c("Control","Drought", "Control",  "Rewetting"))
ggplot(data.agg1, aes(x = Treatment3, y = Keystone, fill=Phylum)) +
    geom_bar(stat='identity') + #, position = "fill"
    labs(x="",y = "No. of keystone OTUs")+
    facet_grid(Habitat~Treatment1, scales="free_x")+
    theme_bw()+  scale_fill_manual(values= col11)+
    theme(strip.text = element_text(size = 8,face="bold"),
          panel.spacing = unit(0, "lines"),
          legend.title = element_text(colour="black", size=8, face="bold"),
          legend.text = element_text(colour="black", size=8, face="bold"),
          axis.text.y=element_text(size=8,face="bold"),
          axis.text.x=element_text(size=8,face="bold"),
          axis.title=element_text(size=8,face="bold"))
ggsave("ZiPi.interBF.KeystoneTaxa.2021.09.03.pdf", width = 6, height = 6)


####################
#Functional Guilds##
####################
library(plyr) 
library(tidyverse) 
mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.cross.BF.ZiPi"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)

PiZi0 = ldply(myfiles, read_csv)
Pi.cutoff=0.62
Zi.cutoff=2.5

PiZi <- PiZi0[PiZi0$network == "Fung-Fung",]
PiZi <- PiZi[PiZi$tpA!= 9,]

PiZi$tpA

PiZi <- droplevels(PiZi[!(PiZi$Habitat=="Leaf" & PiZi$tpA == 2),])

PiZi$Habitat<-factor(PiZi$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
PiZi$Treatment1<-factor(PiZi$tpA, labels = c("Drought period", "Rewetting period"))
PiZi$Treatment2<-factor(PiZi$Treatment, labels = c("Control", "Drought"))
PiZi$Treatment3 <- interaction (PiZi$Treatment1, PiZi$Treatment2)
PiZi$Treatment3 <- factor(PiZi$Treatment3 , labels = c("Control", "Control", "Drought", "Rewetting"))

ggplot(PiZi, aes(x=Pi, y=Zi,  color = Treatment3)) +
  geom_point(size=2, alpha = 0.3)+theme_bw()+facet_grid(Habitat~Treatment1)+xlim(0,1)+
  scale_shape_manual(values=c(17, 16))+
  geom_vline(xintercept = Pi.cutoff, color = "blue", linetype = 3)+
  geom_hline(yintercept = Zi.cutoff, color = "blue", linetype = 3)+
  scale_color_manual(values = c( "black","red", "blue"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.y=element_text(size=8,face="bold"),
        axis.text.x=element_text(size=8,face="bold",angle = 45),
        axis.title=element_text(size=8,face="bold"))
ggsave("Fung.ZiPi.2021.09.03.pdf", width = 6, height = 6)

data<-droplevels(subset(PiZi, Pi > Pi.cutoff | Zi > Zi.cutoff ))
write.csv(data,"Fung.ZiPi.keystone.2021.09.03.csv")

data<-read.csv("Fung.ZiPi.keystone.2021.09.03.csv", head =T)
data$abu <-1
library(splitstackshape)
data1<-data[,c("Treatment", "Phylum","Funguild", "abu","Habitat", "Treatment1" )]

data1$fact<-paste(data1$Treatment, data1$Phylum, data1$Funguild, data1$Habitat, data1$Treatment1, sep=".")
data.agg<-aggregate(data1$abu, by=list(Occurence=data1$fact), FUN=sum)
data.agg1<-cSplit(data.agg, "Occurence", ".")
names(data.agg1) <- c("Occurence", "Treatment", "Phylum", "Funguild","Habitat", "Treatment1")

data.agg1<-droplevels(data.agg1[data.agg1$Phylum!="X_" & data.agg1$Phylum!="Other" & data.agg1$Phylum!="_" & data.agg1$Funguild!="_",  ])
data.agg1$fac <- paste(data.agg1$Treatment,  data.agg1$Habitat, data.agg1$Treatment1, sep=".")


#data.agg1$Phylum
library(reshape2)
data_wide <- dcast(data.agg1,  Funguild ~fac, value.var="Occurence")
data_wide[is.na(data_wide)] = 0

row.names(data_wide)<-data_wide$Funguild
data_wide<-data_wide[,-1]
data_wide <- data_wide[order(-rowSums(data_wide)),]
row.names(data_wide)
fung.L.lev<-data.frame(t(data_wide))
dax<-data.frame(var=row.names(fung.L.lev))
dax<-cSplit(dax, "var", ".")
names(dax)<-c( "Treatment", "Habitat", "Treatment1")

fung.L.lev<-cbind(Group.1=row.names(fung.L.lev),fung.L.lev )

fung.L1<-fung.L.lev# the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ".")
names(fung.L1)<-c("Funguild","Keystone", "Treatment", "Habitat", "Treatment1")

data.agg1<-rbind(fung.L1)
col11<-c("darkblue","red","#ff00ff", "deepskyblue", "gold", "blue", "navy", "darkgreen","black", "orange", "purple", "grey")

data.agg1$Habitat <- factor(data.agg1$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
data.agg1$Treatment <-factor(data.agg1$Treatment, labels = c("Con", "Str"))
data.agg1$Treatment1<-factor(data.agg1$Treatment1, levels = c("Drought period", "Rewetting period"))

data.agg1$Treatment3 <- interaction (data.agg1$Treatment, data.agg1$Treatment1)
data.agg1$Treatment3  <- factor(data.agg1$Treatment3  , labels = c("Control","Drought", "Control",  "Rewetting"))
ggplot(data.agg1, aes(x = Treatment3, y = Keystone, fill=Funguild)) +
    geom_bar(stat='identity') + #, position = "fill"
    labs(x="",y = "No. of keystone OTUs")+
    facet_grid(Habitat~Treatment1, scales="free_x")+
    theme_bw()+  scale_fill_manual(values= col11)+
    theme(strip.text = element_text(size = 8,face="bold"),
          panel.spacing = unit(0, "lines"),
          legend.title = element_text(colour="black", size=8, face="bold"),
          legend.text = element_text(colour="black", size=8, face="bold"),
          axis.text.y=element_text(size=8,face="bold"),
          axis.text.x=element_text(size=8,face="bold"),
          axis.title=element_text(size=8,face="bold"))
ggsave("ZiPi.Fung.KeystoneTaxa.2021.09.03.pdf", width = 6, height = 6)

######
### BAC
#######

library(plyr) 
library(tidyverse) 
mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.cross.BF.ZiPi"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)

PiZi0 = ldply(myfiles, read_csv)
Pi.cutoff=0.62
Zi.cutoff=2.5

PiZi <- PiZi0[PiZi0$network == "Bac-Bac",]
PiZi <- PiZi[PiZi$tpA!= 9,]

#PiZi$tpA

#PiZi <- droplevels(PiZi[!(PiZi$Habitat=="Leaf" & PiZi$tpA == 2),])

PiZi$Habitat<-factor(PiZi$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
PiZi$Treatment1<-factor(PiZi$tpA, labels = c("Drought period", "Rewetting period"))
PiZi$Treatment2<-factor(PiZi$Treatment, labels = c("Control", "Drought"))
PiZi$Treatment3 <- interaction (PiZi$Treatment1, PiZi$Treatment2)
PiZi$Treatment3 <- factor(PiZi$Treatment3 , labels = c("Control", "Control", "Drought", "Rewetting"))

ggplot(PiZi, aes(x=Pi, y=Zi,  color = Treatment3)) +
  geom_point(size=2, alpha = 0.3)+theme_bw()+facet_grid(Habitat~Treatment1)+xlim(0,1)+
  scale_shape_manual(values=c(17, 16))+
  geom_vline(xintercept = Pi.cutoff, color = "blue", linetype = 3)+
  geom_hline(yintercept = Zi.cutoff, color = "blue", linetype = 3)+
  scale_color_manual(values = c( "black","red", "blue"))+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.y=element_text(size=8,face="bold"),
        axis.text.x=element_text(size=8,face="bold",angle = 45),
        axis.title=element_text(size=8,face="bold"))
ggsave("ZiPi.Bac.2021.09.03.pdf", width = 6, height = 6)

data<-droplevels(subset(PiZi, Pi > Pi.cutoff | Zi > Zi.cutoff ))
write.csv(data,"ZiPi.Bac.keystone.2021.09.03.csv")

data<-read.csv("ZiPi.Bac.keystone.2021.09.03.csv", head =T)
data$abu <-1
library(splitstackshape)
data$Kingdom
data1<-data[,c("Treatment","Kingdom", "Phylum","Funguild", "abu","Habitat", "Treatment1" )]

data1$fact<-paste(data1$Treatment, data1$Kingdom,data1$Phylum, data1$Funguild, data1$Habitat, data1$Treatment1, sep=".")
data.agg<-aggregate(data1$abu, by=list(Occurence=data1$fact), FUN=sum)
data.agg1<-cSplit(data.agg, "Occurence", ".")
names(data.agg1) <- c("Occurence", "Treatment", "Kingdom","Phylum", "Funguild","Habitat", "Treatment1")

data.agg1<-droplevels(data.agg1[data.agg1$Phylum!="X_" & data.agg1$Phylum!="Other" & data.agg1$Phylum!="_" & data.agg1$Kingdom!= "Eukaryote",  ])
data.agg1$fac <- paste(data.agg1$Treatment,  data.agg1$Habitat, data.agg1$Treatment1, sep=".")


library(reshape2)
data_wide <- dcast(data.agg1,  Phylum ~fac, value.var="Occurence")
data_wide[is.na(data_wide)] = 0

row.names(data_wide)<-data_wide$Phylum
data_wide<-data_wide[,-1]
data_wide <- data_wide[order(-rowSums(data_wide)),]
row.names(data_wide)
fung.L.lev<-data.frame(t(data_wide))
dax<-data.frame(var=row.names(fung.L.lev))
dax<-cSplit(dax, "var", ".")
names(dax)<-c( "Treatment", "Habitat", "Treatment1")

fung.L.lev<-cbind(Group.1=row.names(fung.L.lev),fung.L.lev )

fung.L1<-fung.L.lev # the domiant OTUs
fung.L1 <- melt(fung.L1,id.vars = "Group.1")
fung.L1<-cSplit(fung.L1, "Group.1", ".")
names(fung.L1)<-c("Phylum","Keystone", "Treatment", "Habitat", "Treatment1")


data.agg1<-fung.L1
col11<-c("darkblue","red","#ff00ff", "deepskyblue", "gold", "blue", "navy", "darkgreen","black", "orange", "purple", "grey")

data.agg1$Habitat <- factor(data.agg1$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
data.agg1$Treatment <-factor(data.agg1$Treatment, labels = c("Con", "Str"))
data.agg1$Treatment1<-factor(data.agg1$Treatment1, levels = c("Drought period", "Rewetting period"))

data.agg1$Treatment3 <- interaction (data.agg1$Treatment, data.agg1$Treatment1)
data.agg1$Treatment3  <- factor(data.agg1$Treatment3  , labels = c("Control","Drought", "Control",  "Rewetting"))
ggplot(data.agg1, aes(x = Treatment3, y = Keystone, fill=Phylum)) +
    geom_bar(stat='identity') + #, position = "fill"
    labs(x="",y = "No. of keystone OTUs")+
    facet_grid(Habitat~Treatment1, scales="free_x")+
    theme_bw()+  scale_fill_manual(values= col11)+
    theme(strip.text = element_text(size = 8,face="bold"),
          panel.spacing = unit(0, "lines"),
          legend.title = element_text(colour="black", size=8, face="bold"),
          legend.text = element_text(colour="black", size=8, face="bold"),
          axis.text.y=element_text(size=8,face="bold"),
          axis.text.x=element_text(size=8,face="bold"),
          axis.title=element_text(size=8,face="bold"))
ggsave("ZiPi.Bac.KeystoneTaxa.2021.09.03.pdf", width = 6, height = 6)




setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")

da1<-read.csv("ZiPi.Bac.keystone.2021.09.03.csv", head = T)
da2<-read.csv("Fung.ZiPi.keystone.2021.09.03.csv", head = T)
da3<-read.csv("interBF.ZiPi.keystone.2021.09.03.csv", head = T)
da4<-read.csv("crossBF.ZiPi.keystone.2021.09.03.csv", head = T)

colnames(da1)
colnames(da2)
colnames(da3)
colnames(da4)

da3$Kingdom2<-NULL
da4$Kingdom2<-NULL
da<-rbind(da1, da2, da3, da4 )

colnames(da)
dax<-da[, c("otu.name", "Kingdom","Phylum", "Class", "Order", "Family","Genus", "Funguild","Habitat", "Treatment1", "Treatment2","network","Zi","Pi", "group")]

colnames(dax) <- c("otu.name", "Kingdom","Phylum", "Class", "Order", "Family","Genus", "Fungal Guild","Compartment", "Time period", "Treatment","Network type","Zi","Pi", "Hub type")

write.csv(dax, "Table.S2.Hubs.csv")

```

```{r}
#################################################
# to rule out the effect of Geographic distance #
#################################################


rm(list=ls())
library(vegan)##decostand
setwd("/Users/chenggao/Google\ Drive/EPICON/BacFunTran")
habitat <- "Leaf"; treatment <- "Control"; tpA <- 2; tpB <- 9; type = "SpMan"; fq <- 7; abu <- 19; 
library(igraph)

dispersal.limitation<-function(habitat, treatment, tpA, tpB) {
  
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  SigCor.tmp0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  
  
  env.tmp0 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/data.env.", habitat, "." ,treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  bac.tmp0 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/data.bac.", habitat, "." ,treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  fung.tmp0 <- readRDS(paste0("BFT.SpMan.df.2021.08.16/data.fung.", habitat, "." ,treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  bacfung.tmp0 <- cbind (bac.tmp0 , fung.tmp0)
  #bacfung.tmp0 <-bac.tmp0
  
  n <-length(SigCor.tmp0$row)
  SigCor.tmp0$ab.mantel.R <- NA
  SigCor.tmp0$ag.mantel.R <- NA
  SigCor.tmp0$bg.mantel.R <- NA
  SigCor.tmp0$ab.mantel.P <- NA
  SigCor.tmp0$ag.mantel.P <- NA
  SigCor.tmp0$bg.mantel.P <- NA
  SigCor.tmp0$dispersallimitation <- NA
  m = 0
  h = 0
  start_time <- Sys.time()
  for (i in c(1:n)) {
    g <- ecodist::distance(cbind(env.tmp0$X, env.tmp0$Y))
    a <- dist(bacfung.tmp0[,as.character(SigCor.tmp0$row[i])])
    b <- dist(bacfung.tmp0[,as.character(SigCor.tmp0$col[i])])
    
    SigCor.tmp0$ab.mantel.R[i] <- mab.r <- mantel(a,b)$statistic
    SigCor.tmp0$ag.mantel.R[i] <- mag.r <- mantel(a,g)$statistic 
    SigCor.tmp0$bg.mantel.R[i] <- mbg.r <- mantel(b,g)$statistic
    SigCor.tmp0$ab.mantel.P[i] <- mab.p <- mantel(a,b)$signif
    SigCor.tmp0$ag.mantel.P[i] <- mag.p <- mantel(a,g)$signif 
    SigCor.tmp0$bg.mantel.P[i] <- mbg.p <- mantel(b,g)$signif
    
    SigCor.tmp0$dispersallimitation <- j <- (mag.r > mab.r & mbg.r > mab.r & mag.p < 0.01 & mbg.p < 0.01 & mab.p < 0.01) 
    
    SigCor.tmp0$dispersallimitation <- k <- (mag.r > mab.r & mbg.r > mab.r ) 
    
    m <- m + j
    h <- h + k
  }
  
  
  dl.sum<-data.frame(habitat, treatment, tpA, tpB, m, h, n)
  saveRDS(dl.sum, paste0("Spearman.BacFun.network.dispersal.limitation.2021.09.07/Spearman.net.disper.limit.", habitat, "." ,treatment,".",tpA,".",tpB,".RDS"))
  
  colnames(dl.sum) <- c()
  print(m)
  print(h)
  print(n)
  
  library(beepr)
  beep()
  
  end_time <- Sys.time()
  end_time - start_time
  
  
}

#dispersal.limitation("Root","Control", 2, 9)
#dispersal.limitation("Root","Pre_flowering_drought", 2, 9)
#dispersal.limitation("Root","Control", 8, 18)
#dispersal.limitation("Root","Pre_flowering_drought", 8, 18)
#dispersal.limitation("Root","Control", 9, 18)
#dispersal.limitation("Root","Post_flowering_drought", 9, 18)

#dispersal.limitation("Rhizosphere","Control", 2, 9)
#dispersal.limitation("Rhizosphere","Pre_flowering_drought", 2, 9)
#dispersal.limitation("Rhizosphere","Control", 8, 18)
#dispersal.limitation("Rhizosphere","Pre_flowering_drought", 8, 18)
#dispersal.limitation("Rhizosphere","Control", 9, 18)
#dispersal.limitation("Rhizosphere","Post_flowering_drought", 9, 18)


#dispersal.limitation("Soil","Control", 2, 9)
#dispersal.limitation("Soil","Pre_flowering_drought", 2, 9)
#dispersal.limitation("Soil","Control", 8, 18)
#dispersal.limitation("Soil","Pre_flowering_drought", 8, 18)
#dispersal.limitation("Soil","Control", 9, 18)
#dispersal.limitation("Soil","Post_flowering_drought", 9, 18)

#dispersal.limitation("Leaf","Control", 2, 9)
#dispersal.limitation("Leaf","Pre_flowering_drought", 2, 9)
#dispersal.limitation("Leaf","Control", 8, 18)
#dispersal.limitation("Leaf","Pre_flowering_drought", 8, 18)
#dispersal.limitation("Leaf","Control", 9, 18)
#dispersal.limitation("Leaf","Post_flowering_drought", 9, 18)
library(beepr)
beep()

mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/Spearman.BacFun.network.dispersal.limitation.2021.09.07"
myfiles = list.files(path=mydir, pattern="*.RDS", full.names=TRUE)
gd = ldply(myfiles, readRDS)
gd$pct <- gd$h/gd$n

gd$tpA <- factor(gd$tpA, labels = c("Drought period", "Rewetting period"))
gd$Treatment<-factor(gd$treatment, labels = c("Control", "Drought" ))
gd$habitat <-factor(gd$habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
gd$Treatment3 <- interaction(gd$tpA, gd$Treatment)
gd$Treatment3 <- factor(gd$Treatment3, labels = c("Control", "Control", "Drought", "Rewetting"))
gd$pct1 <- round((gd$pct * 100),2)

ggplot(gd, aes(x = Treatment3, y = pct, color= Treatment3, label = pct1)) +
  geom_point()+   geom_text(hjust = 0, nudge_x = 0.05,nudge_y = 0.05, fontface = "bold")+
  facet_grid(habitat~tpA, scale="free_x")+theme_bw()+xlab("")+ylab("Taxon-Taxon-Space Association (% network links)")+
  scale_color_manual(values = c("black", "blue", "red"))+
  theme(strip.text = element_text(size = 10,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=10, face="bold"),
        legend.text = element_text(colour="black", size=10, face="bold"),
        axis.text.y=element_text(size=10,face="bold"),
        axis.text.x=element_text(size=10,face="bold",angle = 0),
        axis.title=element_text(size=10,face="bold"))+
  scale_y_continuous(labels = scales::percent, limits = c(0,1))
ggsave("Spearman.net.rule.out.dispersal.limitation.2021.09.07.pdf", width=7, height=5)

```


```{r, message=FALSE, warning=FALSE, fig.height = 6, fig.width = 12}
robusX<-function(habitat, treatment, tpA, tpB){
  BF0<-read.csv("Microbiome/0000BacteriaFungi.1029x1293.13165.2019.07.10.csv", head = T, row.names = 1)
  ID.tmp<-BF0[,c("Kingdom",	"Kingdom1",	"Phylum",	"Class",	"Order",	"Family",	"Genus",	"Funguild",	"OTU.ID",	"Morph",	"Morph1")]
  
  da<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  
  
  g <- graph.data.frame(da, directed=FALSE)
  #igraph 
  rob.1<- robustness(g, type = c("vertex", "edge"), measure = c("btwn.cent",
                                                                "degree", "random"), N = 1000)
  robus<-data.frame(cbind(removed.pct=rob.1$removed.pct, comp.pct=rob.1$comp.pct))
  robus$Habitat<-habitat
  robus$Treatment<-treatment
  robus$tpA<-tpA
  robus$tpB<-tpB
  robus$network <-"CrossBF"
  write.csv(robus, paste0("SpMan.BacFun.network.Robustness/robustness.crossBF.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Eukaryote" & da0$Kingdom.1 == "Eukaryote",]
  g <- graph.data.frame(da, directed=FALSE)
  rob.1<- robustness(g, type = c("vertex", "edge"), measure = c("btwn.cent",  "degree", "random"), N = 1000)
  robus<-data.frame(cbind(removed.pct=rob.1$removed.pct, comp.pct=rob.1$comp.pct))
  robus$Habitat<-habitat
  robus$Treatment<-treatment
  robus$tpA<-tpA
  robus$tpB<-tpB
  robus$network <-"Fun-Fun"
  write.csv(robus, paste0("SpMan.BacFun.network.Robustness/robustness.fung.fung.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom == "Prokaryote" & da0$Kingdom.1 == "Prokaryote",]
  g <- graph.data.frame(da, directed=FALSE)
  rob.1<- robustness(g, type = c("vertex", "edge"), measure = c("btwn.cent",  "degree", "random"), N = 1000)
  robus<-data.frame(cbind(removed.pct=rob.1$removed.pct, comp.pct=rob.1$comp.pct))
  robus$Habitat<-habitat
  robus$Treatment<-treatment
  robus$tpA<-tpA
  robus$tpB<-tpB
  robus$network <-"Bac-Bac"
  write.csv(robus, paste0("SpMan.BacFun.network.Robustness/robustness.bac.bac", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  
  da0<-readRDS(paste0("BFT.",type,".sig.df.2021.08.16/",type,".Rsig.Bac-Fung.",habitat,".", treatment,".",tpA,".",tpB,".",fq,".",abu,".RDS"))
  da <- da0[da0$Kingdom != da0$Kingdom.1 ,]
  g <- graph.data.frame(da, directed=FALSE)
  rob.1<- robustness(g, type = c("vertex", "edge"), measure = c("btwn.cent",  "degree", "random"), N = 1000)
  robus<-data.frame(cbind(removed.pct=rob.1$removed.pct, comp.pct=rob.1$comp.pct))
  robus$Habitat<-habitat
  robus$Treatment<-treatment
  robus$tpA<-tpA
  robus$tpB<-tpB
  robus$network <-"Bac-Fun"
  write.csv(robus, paste0("SpMan.BacFun.network.Robustness/robustness.interBF.", habitat,".",treatment,".",tpA,".", tpB,".csv"))
  

}

library(beepr)
beep()
robusX("Root", "Control", 2, 9)
robusX("Root", "Pre_flowering_drought", 2, 9)
robusX("Root", "Control", 8, 18)
robusX("Root", "Pre_flowering_drought", 8, 18)
robusX("Root", "Control", 9, 18)
robusX("Root", "Post_flowering_drought", 9, 18)
robusX("Rhizosphere", "Control", 2, 9)
robusX("Rhizosphere", "Pre_flowering_drought", 2, 9)
robusX("Rhizosphere", "Control", 8, 18)
robusX("Rhizosphere", "Pre_flowering_drought", 8, 18)
robusX("Rhizosphere", "Control", 9, 18)
robusX("Rhizosphere", "Post_flowering_drought", 9, 18)
robusX("Soil", "Control", 2, 9)
robusX("Soil", "Pre_flowering_drought", 2, 9)
robusX("Soil", "Control", 8, 18)
robusX("Soil", "Pre_flowering_drought", 8, 18)
robusX("Soil", "Control", 9, 18)
robusX("Soil", "Post_flowering_drought", 9, 18)
robusX("Leaf", "Control", 2, 9)
robusX("Leaf", "Pre_flowering_drought", 2, 9)
robusX("Leaf", "Control", 8, 18)
robusX("Leaf", "Pre_flowering_drought", 8, 18)
robusX("Leaf", "Control", 9, 18)
robusX("Leaf", "Post_flowering_drought", 9, 18)
beep()


mydir = "/Users/chenggao/Google\ Drive/EPICON/BacFunTran/SpMan.BacFun.network.Robustness"
myfiles = list.files(path=mydir, pattern="*.csv", full.names=TRUE)

robX = ldply(myfiles, read_csv)
robX<-droplevels(robX[robX$tpA!= 9 &robX$network!="CrossBF",])

robX <- robX[!(robX$Habitat=="Leaf" & robX$network!="Bac-Bac" & robX$tpA==2),]



robX$Treatment1<-factor(robX$tpA, labels = c("Drought period", "Rewetting period"))
robX$Habitat<-factor(robX$Habitat, levels = c("Root", "Rhizosphere", "Soil", "Leaf"))
robX$Treatment<-factor(robX$Treatment, labels = c("Con", "Str"))
ggplot(robX, aes(x = removed.pct, y = comp.pct, color=network,linetype=Treatment)) +
  geom_smooth() +  scale_color_manual(values= c("black", "red","blue", "yellow"))+
  facet_grid(Habitat~Treatment1 + network)+
  theme_bw()+
  theme(strip.text = element_text(size = 8,face="bold"),
        panel.spacing = unit(0, "lines"),
        legend.title = element_text(colour="black", size=8, face="bold"),
        legend.text = element_text(colour="black", size=8, face="bold"),
        axis.text.y=element_text(size=8,face="bold"),
        axis.text.x=element_text(size=8,face="bold",angle = 45),
        axis.title=element_text(size=8,face="bold"))
ggsave("BacFun.network.robustness.2021.09.03.pdf", width = 12, height = 6)

```

